args <- commandArgs(trailingOnly = FALSE)
root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", args, value = TRUE)[1])), ".."), mustWork = FALSE)
Sys.setenv(WHISKER_ROOT = "C:/Users/Sam/Documents/LOL_Whisker")
suppressPackageStartupMessages({ library(yaml); library(jsonlite); library(httr2); library(arrow); library(digest) })
source("C:/Users/Sam/Documents/LOL_Whisker/pipeline/R/00_setup.R")
paths <- whisker_ensure_dirs()
whisker_source_lib(paths)
source(file.path(paths$pipeline, "R", "01_download.R"))
whisker_step_01_download(paths)
